name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: backend/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --working-dir=backend

    - name: Copy .env.example to .env
      run: cp backend/.env.example backend/.env

    - name: Generate application key
      run: php artisan key:generate --working-dir=backend

    - name: Set up database
      run: |
        sudo apt-get install -y postgresql-client
        php artisan config:cache --working-dir=backend
        php artisan migrate --force --working-dir=backend
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: password

    - name: Run tests
      run: php artisan test --working-dir=backend
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: password
